### ISSUE TITLE
您好，如果不想要某家aar，可否删掉？还能保证正常编译？

### ISSUE THREAD

**Issue by justziyang** [TJHello/ADEasy#2]
您好，打扰了，我最近在做一个聚合sdk，遇到一些接入方不想要某家aar的情况，但是我代码会有继承这些aar内的类，导致没办法删掉aar，想问下您这个是不是做了这方便的功能，可否分享下实现思路或者给个名词之类的提示下啊？感谢感谢~

**Comment by TJHello** [comment]
该问题的答案可以通过谷歌或者百度搜索到。但由于我们的ADEasy是闭源性质的，所以我们没办法告知更多，非常抱歉。
