### ISSUE TITLE
作为一个聚合广告sdk,不开源源码，怎么保证不被流量劫持，偷广告流量？

### ISSUE THREAD

**Issue by liang530** [TJHello/ADEasy#4]
如题，免费是免费了，不开源的话，用不放心啊，别辛苦买的流量走的不是我自己的广告就悲剧了……

**Comment by TJHello** [comment]
不开源只是因为不想让自己努力的成果轻易被人拿到。免费只是针对单机的，我们后面会有收费功能，作为赢利点。
至于盗流量：
1、我们承诺ADEasy只是纯工具SDK，绝对不会在任何情况下，不经过用户同意就使用用户的任何流量。(不排除后面会增加流量置换功能，但肯定是由用户主动开启的)
2、市面上的变现平台，需要开通变现功能，都需要经过签名验证。我没有你的应用签名，是无法做到这点的。
3、开源我们会考虑在后面一些选择开源比较旧的代码。

最后，第一点的承诺，我们会明文声明。希望我们能够合作。
