### ISSUE TITLE
8.3.2102-t42  引用

### ISSUE THREAD

**Issue by Oyama-Oyama** [TJHello/ADEasy#6]
![截屏2021-11-09 下午4 29 43](https://user-images.githubusercontent.com/17978212/140889312-ac89e8c9-cace-4e3f-b2bc-a723317d99de.png)

**Comment by Oyama-Oyama** [comment]
引用以后    build直接报这个错误，引用错了吗？

**Comment by Oyama-Oyama** [comment]
怎么去掉umeng？

**Comment by Oyama-Oyama** [comment]
顺便问下  是不是不使用umeng 就不需要调用agreePrivacy这个接口了，这里面的privacy包含哪些平台的政策？

**Comment by TJHello** [comment]
抱歉，我不经常看github，有需要请通过我的联系邮箱联系我。
